Sftp pester fixes
PowerShell/openssh-portable pull request #100
Opened 2017-03-30 20:13 UTC by bagajjal

https://github.com/PowerShell/Win32-OpenSSH/issues/637
https://github.com/PowerShell/Win32-OpenSSH/issues/638

2017-03-30 20:18 UTC, manojampalam commented on regress/pesterTests/SCP.Tests.ps1
> +            Clear-Content "$($OpenSSHTestInfo['OpenSSHBinPath'])\logs\ssh-agent.log" -Force -ErrorAction ignore
Clever change :). Will save on test run time.

2017-03-30 20:18 UTC, manojampalam approved these changes

2017-03-30 22:56 UTC, bingbing8 requested changes

2017-03-30 22:56 UTC, bingbing8 commented on regress/pesterTests/README.md
> +$env:path = "<sshd.exe directory path>;$env:path"
This step is not required. User can specify -OpenSSHBinPath to Setup-OpenSSHEnvironment. Setting the path should be part of the Setup-OpenSSHEnvironment.

2017-03-30 22:56 UTC, bingbing8 commented on regress/pesterTests/README.md
> +$OpenSSHTestInfo["DebugMode"] = $true
All the values in the hash table can be set by this one. We can probably  use DebugMode as a sample.

2017-03-30 22:56 UTC, bingbing8 commented on regress/pesterTests/README.md
> +$OpenSSHTestInfo (Verify DebugMode is set to true)
Since this is showing as running command in powershell prompt. the later parts of the line needs to change to show it is a comment instead of part of command.

2017-03-30 22:56 UTC, bingbing8 commented on regress/pesterTests/README.md
> +C:\git\openssh-portable\regress\pesterTests\SCP.Tests.ps1
this is duplicate with the above section. My suggestion is to have a section mentioned that all the values in the hash table can be updated by this way and take effect in the subsequent test runs.

2017-03-31 00:46 UTC, bagajjal commented
Will raise a different review as I'm having some issue pushing changes to this remote branch SFTPPesterFixes

2017-03-31 00:46 UTC, closed without merging