Add file permission check for ssh_config and authorized_keys
PowerShell/openssh-portable pull request #110
Opened 2017-04-13 08:43 UTC by bingbing8

https://github.com/PowerShell/Win32-OpenSSH/issues/644
https://github.com/PowerShell/Win32-OpenSSH/issues/588
https://github.com/PowerShell/Win32-OpenSSH/issues/667

2017-04-13 23:33 UTC, bingbing8 commented on contrib/win32/win32compat/w32-permcheck.c
> +				debug3("Bad permission on %s", name);
more details can be logged

2017-04-13 23:33 UTC, bingbing8 commented on contrib/win32/win32compat/w32-permcheck.c
> +				debug3("Bad permission on %s", name);
more details needs to logged.

2017-04-13 23:33 UTC, bingbing8 commented on contrib/win32/win32compat/w32-permcheck.c
> +is_admin_user(PSID user_sid)
local utility static

2017-04-14 01:12 UTC, bagajjal requested changes

2017-04-14 01:12 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +		debug3("failed to retrieve the owner sid and dacl of file %s with error code: %d", name, ret);
error code is not printed correctly (ret is not error code)..
I would suggest adding bool variables for the IsValidSid / IsValidAcl and add that to debug3 so that the log will be very clear for debugging.

2017-04-14 01:12 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +* To Check if the user have right owner and permission set.
Please update the comments with the logic below (which user accounts you are assuming valid and what permissions you are checking)..

2017-04-14 01:12 UTC, bagajjal commented on contrib/win32/win32compat/ssh-agent/agentconfig.c
> +		if ((config_file_name = utf16_to_utf8(path)) == NULL)
The TODO on line 101 is still valid? we do handle the Unicode paths here?

2017-04-14 01:12 UTC, bagajjal commented on contrib/win32/win32compat/ssh-agent/agentconfig.c
> +static int
good job to align the code with coding guidelines...

2017-04-14 01:12 UTC, bagajjal commented on contrib/win32/win32compat/ssh-agent/agentconfig.c
> +				(user = utf16_to_utf8(wuser)) == NULL)
alignment issue

2017-04-14 01:12 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +* Support file permission check functions' replacements needed to let the
Plz rephrase for better readability.

2017-04-14 01:12 UTC, bagajjal commented on sshfileperm.h
> +#ifndef _SSH_FILE_PERM_H
pragma once..

We should be consistent whether to use the preprocessor guards or pragma once.. I believe we are using "pragma once"..

2017-04-14 22:15 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +* To Check if the user have right owner and permission set.
the user in the pwd

2017-04-15 21:09 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +* Support file permission check functions' replacements needed to let the
fixed in next push

2017-04-15 21:25 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +* To Check if the user have right owner and permission set.
I updated the comments. Please check if it is clear.

2017-04-15 21:28 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +		debug3("failed to retrieve the owner sid and dacl of file %s with error code: %d", name, ret);
the ret is the error code (https://msdn.microsoft.com/en-us/library/windows/desktop/aa446645(v=vs.85).aspx). I will use different var to be clear.
added var to log the return of IsValidSid / IsValidAc

2017-04-15 21:39 UTC, bingbing8 commented on contrib/win32/win32compat/ssh-agent/agentconfig.c
> +		if ((config_file_name = utf16_to_utf8(path)) == NULL)
deleted the comments

2017-04-15 21:39 UTC, bingbing8 commented on contrib/win32/win32compat/ssh-agent/agentconfig.c
> +				(user = utf16_to_utf8(wuser)) == NULL)
fixed the whole file

2017-04-15 21:40 UTC, bingbing8 commented on sshfileperm.h
> +#ifndef _SSH_FILE_PERM_H
I keeps it consistent to other file in libssh. for example, auth.h

2017-04-21 23:23 UTC, bagajjal requested changes

2017-04-21 23:23 UTC, bagajjal commented on authfile.c
> +	if (set_secure_file_permission(filename, NULL) != 0)
please add comments why is it required and what permissions we are setting..

2017-04-21 23:23 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +	swprintf(sddl, 255, L"D:P(A;;FA;;;%s)", sid_utf16);
replace 255 with sizeof(sddl)-1

2017-04-21 23:23 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +		errno = ENOMEM;
add a debug log

2017-04-21 23:23 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +		errno = ENOMEM;
add a debug log

2017-04-21 23:23 UTC, bagajjal commented on contrib/win32/win32compat/w32-sshfileperm.c
> +	if (ConvertStringSidToSid(pwd->pw_sid, &owner_sid) == FALSE) {
create a function that takes the stringsid and returns the sid in utf16.. this might be useful in future as well..

2017-04-21 23:23 UTC, bagajjal commented on authfile.c
> +
remove this new line

2017-04-24 05:36 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +	if (ConvertStringSidToSid(pwd->pw_sid, &owner_sid) == FALSE) {
but the function you mentioned is not needed here. Here is to convert the urf8 string to a sid.

2017-04-24 19:39 UTC, bingbing8 commented on authfile.c
> +
fixed

2017-04-24 19:46 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +	swprintf(sddl, 255, L"D:P(A;;FA;;;%s)", sid_utf16);
fixed

2017-04-24 19:46 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +		errno = ENOMEM;
fixed

2017-04-24 19:53 UTC, bingbing8 commented on authfile.c
> +	if (set_secure_file_permission(filename, NULL) != 0)
fixed

2017-04-24 20:01 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +	if (ConvertStringSidToSid(pwd->pw_sid, &owner_sid) == FALSE) {
talked to Balu offline. no need to for this change.

2017-04-24 20:09 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> +		errno = ENOMEM;
fixed

2017-05-01 18:35 UTC, bagajjal approved these changes

2017-05-01 18:35 UTC, bagajjal commented on contrib/win32/openssh/OpenSSHTestHelper.psm1
>          if( ($continue -eq "") -or ($continue -ieq "Y") -or ($continue -ieq "Yes") )
we are not doing anything in this if loop? do we need it?

2017-05-01 18:42 UTC, bingbing8 commented on contrib/win32/openssh/OpenSSHTestHelper.psm1
>          if( ($continue -eq "") -or ($continue -ieq "Y") -or ($continue -ieq "Yes") )
I can change it to elseif ( ($continue -ne "") -and ($continue -ine "Y") -and ($continue -ine "Yes") )
but will do it in next PR to avoiding rerun all tests this time.

2017-05-01 18:47 UTC, bingbing8 commented on contrib/win32/openssh/OpenSSHTestHelper.psm1
>          if( ($continue -eq "") -or ($continue -ieq "Y") -or ($continue -ieq "Yes") )
fixed.

2017-05-01 21:18 UTC, merged