fix for issue 685
PowerShell/openssh-portable pull request #122
Opened 2017-04-25 22:25 UTC by bingbing8

fix for issue that ssh-keygen exit after prompt the user if he/she want to override the existing file.

2017-04-25 23:10 UTC, bagajjal requested changes

2017-04-25 23:10 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
>  			errno = EINVAL;
Please add a error log

2017-04-25 23:10 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +			cp++;
cp should be incremented by the strlen(str_tmp)

2017-04-25 23:10 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +				memcpy(cp, str_tmp, strlen(str_tmp) + 1);
why +1? is it for '\0'?
If yes then we can do it in the end before returning.. not required for every byte.. this might confuse us.

2017-04-25 23:10 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +	char *ret = NULL, *str_tmp = NULL, *cp = NULL;
ret is not required. we can return str itself?

2017-04-25 23:10 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +			if((actual_read + strlen(str_tmp)) < n) {
I think we can remove this if/else and add it as part of the while condition..

} while ( (actual_read = (actual_read + strlen(str_tmp)) && *str_tmp != '\n');

though line 321 is required.

2017-04-26 00:11 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +	char *ret = NULL, *str_tmp = NULL, *cp = NULL;
No, according to https://linux.die.net/man/3/fgets, only return str on success; will return NULL on error

2017-04-26 00:14 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
>  			errno = EINVAL;
added

2017-04-26 00:14 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +			cp++;
fixed

2017-04-26 00:15 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +				memcpy(cp, str_tmp, strlen(str_tmp) + 1);
yes, for '\0'.

2017-04-26 00:17 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +			if((actual_read + strlen(str_tmp)) < n) {
No, we need to check it before copying. otherwise, we may copy more than n.

2017-04-26 00:33 UTC, bagajjal approved these changes

2017-04-26 00:33 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +	char *ret = NULL, *str_tmp = NULL, *cp = NULL;
I mean, ret variable is not required.. we can still use str variable itself..at the start of the function initialize str to NULL and everywhere return str..
Its a minor comment, fix as you like.

2017-04-26 00:34 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +	char *ret = NULL, *str_tmp = NULL, *cp = NULL;
No, str is pre-allocated memory in caller function

2017-04-27 18:43 UTC, manojampalam commented on contrib/win32/win32compat/misc.c
> +			if ((str_tmp = utf16_to_utf8(str_w)) == NULL) {
utf16_to_utf8 will alloc memory for each call. To optimize, you may create a static buffer (to accommodate 2 utf-8 character, max 8 bytes) and call WideCharToMultiByte directly)

2017-04-27 18:44 UTC, manojampalam commented on contrib/win32/win32compat/misc.c
> +			if (fgetws(str_w, 2, stream) == NULL)
This will not work for UTF-16 charecters that will occupy 2 wide chars (or 4 bytes)

2017-04-27 18:44 UTC, manojampalam approved these changes
Create a new issue to address comments below

2017-04-27 18:47 UTC, merged