Add mode support in open() and onboard file perm related changes and tests
PowerShell/openssh-portable pull request #145
Opened 2017-05-22 20:25 UTC by bingbing8

https://github.com/PowerShell/Win32-OpenSSH/issues/710
https://github.com/PowerShell/Win32-OpenSSH/issues/725

2017-05-23 05:49 UTC, manojampalam requested changes
comments inline..

2017-05-23 05:49 UTC, manojampalam commented on contrib/win32/win32compat/fileio.c
> +	wchar_t sddl[256] = { 0 }, owner_ace[100] = {0}, everyone_ace[100] = {0};
Put these static limits in MACROS. Add comments to indicate how the buffer limits are derived. Ex. links to msdn detailing these limits.

2017-05-23 05:49 UTC, manojampalam commented on contrib/win32/win32compat/fileio.c
> +		swprintf(owner_ace, sizeof(owner_ace)/sizeof(wchar_t) - 1, L"(A;;%s;;;%s)", owner_access, sid_utf16);
Use the secure version of swprintf (https://msdn.microsoft.com/en-us/library/ybk95axf.aspx).

2017-05-23 05:49 UTC, manojampalam commented on contrib/win32/win32compat/w32-sshfileperm.c
>  * direct user accounts in local administrators, or user represented by pw
remove this comment

2017-05-23 05:49 UTC, manojampalam commented on readconf.c
> +		implementation on windows to make sure the config file is owned by a user, administrators group, or LOCALSYETEM account
LOCALSYSTEM (instead of LOCALSYETEM)

2017-05-23 23:35 UTC, bingbing8 commented on readconf.c
> +		implementation on windows to make sure the config file is owned by a user, administrators group, or LOCALSYETEM account
fixed

2017-05-23 23:35 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
>  * direct user accounts in local administrators, or user represented by pw
fixed

2017-05-23 23:35 UTC, bingbing8 commented on contrib/win32/win32compat/fileio.c
> +		swprintf(owner_ace, sizeof(owner_ace)/sizeof(wchar_t) - 1, L"(A;;%s;;;%s)", owner_access, sid_utf16);
fixed

2017-05-23 23:35 UTC, bingbing8 commented on contrib/win32/win32compat/fileio.c
> +	wchar_t sddl[256] = { 0 }, owner_ace[100] = {0}, everyone_ace[100] = {0};
fixed

2017-05-24 04:29 UTC, bingbing8 commented
@manojampalam, I update the code for your feedback. Please review. Thanks!
@bagajjal, I include keyutils.tests.ps1 changes. please review. thanks!

2017-05-24 04:44 UTC, manojampalam approved these changes

2017-05-24 04:45 UTC, merged

2017-05-24 18:15 UTC, bagajjal commented on regress/pesterTests/KeyUtils.Tests.ps1
> +			cmd /c "ssh-keyscan -p 22 github.com 2>&1 > $outputFile"
please change replace GitHub.com with 127.0.0.1 for all the ssh-keyscan testcases
			cmd /c "ssh-keyscan -p $port 127.0.0.1 2>&1 > outputFile"
			$outputFile  | Should Contain '.*ssh-rsa.*'

2017-05-24 18:15 UTC, bagajjal commented on contrib/win32/win32compat/w32fd.c
> +	if (flags & O_CREAT) {
why is this code specific to 0_CREAT? this can be called from anywhere with a read flag and a specific mode parameters..