win32: Fix enumerate root dir content on SFTP-server
PowerShell/openssh-portable pull request #148
Opened 2017-05-24 08:14 UTC by remittor

2017-05-24 19:02 UTC, bagajjal requested changes

2017-05-24 19:02 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +		buf->st_mode = _S_IFDIR | _S_IREAD | 0xFF;
0xff is not required here?

2017-05-24 19:02 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +		buf->st_dev = USHRT_MAX;   // rootdir flag
Use ATTR_ROOTDIR  to be consistent..

2017-05-24 19:02 UTC, bagajjal commented on contrib/win32/win32compat/win32_dirent.c
> +		if (!x || totalNumberOfBytes.QuadPart == 0)
I think, we can remove "totalNumberOfBytes.QuadPart == 0"

2017-05-24 23:36 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +	if (path && strcmp(path, "/") == 0) {
from winscp (or) any other third party software.. if we receive "/" then here it is treated as the root dir....

![image](https://cloud.githubusercontent.com/assets/23668037/26429965/17a3478a-409f-11e7-8c25-d771455f20f3.png)

2017-05-25 08:45 UTC, remittor commented on contrib/win32/win32compat/win32_dirent.c
> +		if (!x || totalNumberOfBytes.QuadPart == 0)
Var **totalNumberOfBytes.QuadPart** equ 0 when CD-drive have not CD-disk.

2017-05-25 08:48 UTC, remittor commented on contrib/win32/win32compat/fileio.c
> +	if (path && strcmp(path, "/") == 0) {
I tested this PR in **WinSCP** and **Bitvise** SFTP-clients.

2017-05-25 08:51 UTC, remittor commented on contrib/win32/win32compat/fileio.c
> +		buf->st_dev = USHRT_MAX;   // rootdir flag
**ATTR_ROOTDIR** is 32 bit
**buf->st_dev** is 16 bit

2017-05-25 17:54 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +		buf->st_dev = USHRT_MAX;   // rootdir flag
what is the need for setting this here as we are not using this any where else?

2017-05-26 06:22 UTC, remittor commented on contrib/win32/win32compat/fileio.c
> +		buf->st_dev = USHRT_MAX;   // rootdir flag
You can remove this line, if it so cuts your eyes.

2017-05-26 17:18 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +		buf->st_dev = USHRT_MAX;   // rootdir flag
We should remove the unnecessary code so its easy to maintain the long run..

2017-05-26 18:24 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +		buf->st_mode = _S_IFDIR | _S_IREAD | 0xFF;
I think this can also be removed..

2017-05-26 22:54 UTC, merged