build without OpenSSL.
PowerShell/openssh-portable pull request #17
Opened 2016-11-22 20:50 UTC by arif-pragmasys

Only curve25519 and ed25519 supported

2016-11-22 20:56 UTC, manojampalam requested changes

2016-11-22 20:56 UTC, manojampalam commented on openbsd-compat/arc4random.c
> +#ifdef WINDOWS
Please put a TODO comment here to take care of replacing rand() with a more secure generator.

2016-11-22 20:56 UTC, manojampalam commented on openbsd-compat/arc4random.c
> +#ifdef WINDOWS
Please put a TODO comment here to take care of replacing rand() with a more secure generator. You may look at other TODOs in the sources

2016-11-22 21:06 UTC, arif-pragmasys commented on openbsd-compat/arc4random.c
> +#ifdef WINDOWS
TODO comment added

2016-11-23 07:59 UTC, manojampalam commented
Manually squashed and merged

2016-11-23 07:59 UTC, closed without merging