Fixed ACLs already contain SIDS under Nano
PowerShell/openssh-portable pull request #180
Opened 2017-07-04 12:46 UTC by DarwinJS

This appears to fix https://github.com/PowerShell/Win32-OpenSSH/issues/794.
After modifications were made, retested under Windows 10 and Windows 7 and retested uninstall on both those and Nano.

2017-07-04 12:46 UTC, msftclas commented
@DarwinJS,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-07-06 17:26 UTC, bingbing8 commented on contrib/win32/openssh/OpenSSHUtils.psm1
> +        }
line 353 -- 362 should be in the else block right after line 351.

2017-07-06 17:32 UTC, bingbing8 requested changes

2017-07-06 17:32 UTC, bingbing8 commented on contrib/win32/openssh/OpenSSHUtils.psm1
>              $idRefShortValue = ($a.IdentityReference.Value).split('\')[-1]
line 353-362 should be in else statement right after line 351

2017-07-06 19:01 UTC, DarwinJS commented on contrib/win32/openssh/OpenSSHUtils.psm1
>              $idRefShortValue = ($a.IdentityReference.Value).split('\')[-1]
I wasn't sure about that since I don't know the conditions under which the reference could be $null in the first place.

2017-07-06 21:28 UTC, bingbing8 commented on contrib/win32/openssh/OpenSSHUtils.psm1
>              $idRefShortValue = ($a.IdentityReference.Value).split('\')[-1]
actually never mind. $IdentityReferenceSid is not #null in the first condition.

2017-07-06 21:29 UTC, bingbing8 approved these changes

2017-07-06 21:34 UTC, merged