Terminal fixes
PowerShell/openssh-portable pull request #182
Opened 2017-07-06 19:36 UTC by bagajjal

https://github.com/PowerShell/Win32-OpenSSH/issues/799

Terminal code cleanup and control sequence handling..

2017-07-06 22:51 UTC, bingbing8 approved these changes

2017-07-06 22:51 UTC, bingbing8 commented on contrib/win32/win32compat/shell-host.c
> +	int buf_len = 0;
can you declare those variables before calling utf8_to_utf16, so the check on return can be right after the call?

2017-07-18 05:48 UTC, manojampalam commented on contrib/win32/win32compat/termio.c
> +				if (!SetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), dwAttributes))
If console attributes are changed, they need to be reset to their original once done. 

Quick fix would be to save the original attributes and revert after ReadLine returns.

2017-07-18 05:49 UTC, manojampalam requested changes
comments inline

2017-07-18 19:29 UTC, manojampalam approved these changes

2017-07-18 19:31 UTC, merged