Issue13
PowerShell/openssh-portable pull request #184
Opened 2017-07-14 21:13 UTC by bingbing8

2017-07-17 22:09 UTC, manojampalam commented on contrib/win32/win32compat/console.c
> +				if (memcpy_s(&visibleWindowRect, sizeof(visibleWindowRect), &consoleInfo.srWindow, sizeof(visibleWindowRect))) {
check usage of memcpy_s for return value

2017-07-17 22:10 UTC, manojampalam commented on contrib/win32/win32compat/pwd.c
> +			memcpy_s(head, program_dir_len + shell_host_len + 1, w32_programdir(), program_dir_len);
what if this fails?

2017-07-17 22:12 UTC, manojampalam commented on contrib/win32/win32compat/w32-sshfileperm.c
> -	full_name[domain_name_length] = L'\\';
What issue was this causing (why was it replaced with wcsncat_s that is less performant)?

2017-07-17 22:13 UTC, manojampalam commented on contrib/win32/win32compat/w32log.c
> +		wcsncat_s(log_file, PATH_MAX + 12, L"log", 3);
Double check we are generating the logs right. I believe we don't have any automated test cases to verify this.

2017-07-17 22:13 UTC, manojampalam requested changes
comments inline...

2017-07-17 22:30 UTC, bingbing8 commented on contrib/win32/win32compat/console.c
> +				if (memcpy_s(&visibleWindowRect, sizeof(visibleWindowRect), &consoleInfo.srWindow, sizeof(visibleWindowRect))) {
the if condition is to check the return value

2017-07-17 22:32 UTC, bingbing8 commented on contrib/win32/win32compat/w32log.c
> +		wcsncat_s(log_file, PATH_MAX + 12, L"log", 3);
this is for the log file. I checked, it generate the right log files

2017-07-17 23:20 UTC, bagajjal requested changes

2017-07-17 23:20 UTC, bagajjal commented on contrib/win32/win32compat/console.c
> +		error("Error from vsnprintf_s!");
need to return in the error case

2017-07-17 23:20 UTC, bagajjal commented on contrib/win32/win32compat/console.c
> +
This else now refers to the if (memcpy_s) loop above but it has to be the if (GetConsoleScreenBufferInfo)

2017-07-17 23:20 UTC, bagajjal commented on regress/unittests/win32compat/file_tests.c
> +		//f = open(tmp_filename, O_WRONLY | O_CREAT | O_TRUNC);
why is it failing now but not earlier?

2017-07-18 03:34 UTC, bingbing8 commented on contrib/win32/win32compat/w32-sshfileperm.c
> -	full_name[domain_name_length] = L'\\';
To save lines of code and also don't need to calculate the position. For perf reason, I will change it back.

2017-07-18 03:34 UTC, bingbing8 commented on contrib/win32/win32compat/console.c
> +		error("Error from vsnprintf_s!");
error will exit

2017-07-18 03:35 UTC, bingbing8 commented on regress/unittests/win32compat/file_tests.c
> +		//f = open(tmp_filename, O_WRONLY | O_CREAT | O_TRUNC);
it saw it failed earlier on some machine. It is just not reliable.

2017-07-18 04:58 UTC, bingbing8 commented on contrib/win32/win32compat/pwd.c
> +			memcpy_s(head, program_dir_len + shell_host_len + 1, w32_programdir(), program_dir_len);
fixed

2017-07-18 05:06 UTC, manojampalam commented on contrib/win32/win32compat/console.c
> +				if (memcpy_s(&visibleWindowRect, sizeof(visibleWindowRect), &consoleInfo.srWindow, sizeof(visibleWindowRect))) {
does memcpy_s set errno? you are logging it in the trace below.

2017-07-18 05:23 UTC, bingbing8 commented on contrib/win32/win32compat/console.c
> +				if (memcpy_s(&visibleWindowRect, sizeof(visibleWindowRect), &consoleInfo.srWindow, sizeof(visibleWindowRect))) {
yes, the next line log the errno.

2017-07-18 05:25 UTC, bingbing8 commented on contrib/win32/win32compat/console.c
> +
fixed

2017-07-18 16:45 UTC, bingbing8 commented
@manojampalam @bagajjal please review the latest updates.

2017-07-18 18:07 UTC, manojampalam commented on contrib/win32/win32compat/console.c
> +			if (memcpy_s(&visibleWindowRect, sizeof(visibleWindowRect), &consoleInfo.srWindow, sizeof(visibleWindowRect))) {
memcpy_s doesn't set errno. check https://msdn.microsoft.com/en-us/library/wes2t00f.aspx. If so, the trace below (and other places memcpy_s is used) is not accurate.

2017-07-18 19:30 UTC, bingbing8 commented on contrib/win32/win32compat/console.c
> +			if (memcpy_s(&visibleWindowRect, sizeof(visibleWindowRect), &consoleInfo.srWindow, sizeof(visibleWindowRect))) {
If execution is allowed to continue, these functions return EINVAL and set errno to EINVAL.

2017-07-18 22:21 UTC, bagajjal commented on contrib/win32/win32compat/console.c
> +				error("memcpy_s failed: %d.", r);
1) error("memcpy_s failed, error: %d.", r);
2) This change has to be made at all the places?

2017-07-19 05:01 UTC, bingbing8 commented on contrib/win32/win32compat/console.c
> +				error("memcpy_s failed: %d.", r);
fixed

2017-07-19 21:36 UTC, manojampalam approved these changes

2017-07-19 21:36 UTC, manojampalam commented
Ensure you set errno on failure paths for all POSIX API implementations (ex socketio_recv)

2017-07-19 22:28 UTC, merged