fix the CRLF issue
PowerShell/openssh-portable pull request #204
Opened 2017-09-01 21:55 UTC by bagajjal

https://github.com/PowerShell/Win32-OpenSSH/issues/861

2017-09-02 00:54 UTC, bingbing8 requested changes

2017-09-02 00:54 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +	user_name_utf16 = utf8_to_utf16(user_name);
user_name_utf16  needs to be free

2017-09-02 00:54 UTC, bingbing8 commented on contrib/win32/win32compat/misc.c
> +		wchar_t local_user_fmt_utf16[256] = { 0, };
again, can we use UNCLEN + DNLEN + 2?

2017-09-05 18:50 UTC, DHowett-MSFT commented
This pull request seems to be two different pull requests stuck together. The user/group changes should not be causing the CRLF breakage in Nano, right?

2017-09-05 18:57 UTC, bagajjal commented
@DHowett-MSFT - Yes, user/group related changes are the review comments from another PR... The original PR related to user/group is closed so I am fixing the  user/group related changes here... I have updated the description to make it explicit.

2017-09-05 19:18 UTC, bingbing8 approved these changes

2017-09-05 19:41 UTC, merged