dirent cleanup
PowerShell/openssh-portable pull request #47
Opened 2017-01-10 21:07 UTC by manojampalam

2017-01-10 21:13 UTC, bingbing8 reviewed
test

2017-01-11 00:20 UTC, bingbing8 commented on contrib/win32/win32compat/win32_dirent.c
> + * Open a directory stream on NAME.
Why the NAME is capitalized?

2017-01-11 00:43 UTC, bingbing8 commented on contrib/win32/win32compat/win32_dirent.c
>  		}
for line 134: strncpy(pdirentry->d_name, tmp, strlen(tmp) + 1);
Should it be strncpy(pdirentry->d_name, tmp, sizeof(pdirentry->d_name)); ?

2017-01-13 22:48 UTC, bagajjal requested changes

2017-01-13 22:48 UTC, bagajjal commented on contrib/win32/win32compat/win32_dirent.c
> +		/* breached MAX_PATH */
swprintfreturns the number of wide characters stored in buffer, not counting the terminating null wide character. so this comment "breached MAX_PATH" is misleading? 

If we are unable to write to searchstr then we will be inside if loop.

2017-01-13 22:48 UTC, bagajjal commented on contrib/win32/win32compat/win32_dirent.c
>          free (dirp);
we have to free(dirp) irrespective of dirp->hFile.. so plz move this out of if loop..

2017-01-13 22:48 UTC, bagajjal commented on contrib/win32/win32compat/win32_dirent.c
> +	struct dirent *pdirentry = NULL;
plz update the code as I have modified this to static to avoid the memory leaks..

2017-01-13 22:48 UTC, bagajjal commented on contrib/win32/win32compat/win32_dirent.c
> +		dirp->first = 0;
this will execute everytime even though it is 0 so better to move it inside if loop at line 116.

2018-02-23 21:33 UTC, closed without merging