SFTP bug fixes
PowerShell/openssh-portable pull request #53
Opened 2017-01-13 04:01 UTC by bagajjal

1) bug #479 - "ls c:" is not working
   sanitized_path() will now call realpath() so that we will expand the relative paths to handle all the edge cases like "x:"

2) bug #476 - "cd c:" is not working
   If "c:" is passed to _fullpath() then it is returning existing path but not "c:", so if we append "\\" to "c:" then it is working fine.

3) bug #474 - code cleanup MAX_PATH
   Using PATH_MAX variable instead of MAX_PATH
   In dirent.h, used PATH_MAX instead of hardcoding 256 characters

4) bug #467 - SFTP rename failed if the newpath already exists.
    The _wrename throws error if the newpath exists.
	To make it consistent with the linux behavrior,
     a) if the newpath is a file and if it exists then delete it so that _wrename will succeed.
	 b) if the newpath is a directory and if it is empty then delete it so that _wrename will succeed.

2017-01-13 18:51 UTC, manojampalam requested changes

2017-01-13 18:51 UTC, manojampalam commented on contrib/win32/win32compat/misc.c
> +	// 1) if the new_name is file, then delete it so that _wrename will succeed.
use /* comments */

2017-01-13 18:51 UTC, manojampalam commented on contrib/win32/win32compat/misc.c
> +				struct dirent *dp = readdir(dirp);
free(dp) ?

2017-01-13 18:51 UTC, manojampalam commented on contrib/win32/win32compat/misc.c
> +		if (strlen(resolved) == 2) { // make "x:" as "x:/"
Take it out of parent if. to take care of x: input (expected output x:/)

2017-01-13 18:51 UTC, manojampalam commented on contrib/win32/win32compat/misc.c
> +	if (realpath(path, tempPath)) {
get rid of realpath to avoid unnecessary return value handling

2017-01-13 22:05 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +				struct dirent *dp = readdir(dirp);
as per our discussion.. readdir() will return the static pointer so free(dp) is not required here..

2017-01-14 06:37 UTC, manojampalam approved these changes

2017-01-15 06:12 UTC, merged