win32: Fix execute SSHD child process from "Program Files" directory
PowerShell/openssh-portable pull request #59
Opened 2017-01-20 13:15 UTC by remittor

If current directory is **"C:\Program Files\sshd"**, then function **spawn_child** may be work incorrect.
WinAPI function **GetCommandLineW** may be return only filename, without path.

2017-02-03 23:03 UTC, bagajjal requested changes

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +} while(0)
why do we need do/while(0)?

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +} while(0)
move this to misc_internal.h so that it can be used in all places.

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +			cmdlen += 2 + wcslen(av[i]) + 1;
why are we adding 2 and 1 here? Please add comments.

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +			wprogdir = utf8_to_utf16(w32_programdir());
use progdir instead of w32_programdir()

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +int spawn_child_vp(char * path, char ** argv, int in, int out, int err, DWORD flags) {
rename path to cmd as we pass the cmd here not the path?

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +	if (sw_add_child(pi.hProcess, pi.dwProcessId) == -1) {
couldn't find this, where is it defined?

2017-02-03 23:03 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +	CloseHandle(pi.hThread);
before your code changes, we used to execute this "CloseHandle(pi.hThread);" only when register_child() fails but now we are doing in all the cases.. Did you check if it causes any problem?

2017-02-04 07:04 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +	CloseHandle(pi.hThread);
If **Thread Handle** not using after **CreateProcess**, then need close this handle!!!
Function sw_remove_child_at_index close only **Process Handle** (proof: https://github.com/PowerShell/openssh-portable/blob/fb511200930e9f78481154215aab8a7e5e1df5d9/contrib/win32/win32compat/signal_sigchld.c#L77)

2017-02-04 07:08 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +} while(0)
Ok. Fix this.

2017-02-04 07:20 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +int spawn_child_vp(char * path, char ** argv, int in, int out, int err, DWORD flags) {
I named, by analogy with **execv** function: https://www.freebsd.org/cgi/man.cgi?query=execv
In the future will need replace the call **spawn_child** to call **spawn_child_vp**:
1) https://github.com/PowerShell/openssh-portable/blob/c6b57c018c3ea532854c404c9be194bce6cb51e2/scp.c#L315
2) https://github.com/PowerShell/openssh-portable/blob/c6b57c018c3ea532854c404c9be194bce6cb51e2/sftp.c#L2351

2017-02-04 07:22 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +			cmdlen += 2 + wcslen(av[i]) + 1;
+2: one space and one quote
+1: one quote
Ok. Fix this.

2017-02-04 07:23 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +			wprogdir = utf8_to_utf16(w32_programdir());
Ok. Fix this.

2017-02-04 07:23 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +	if (sw_add_child(pi.hProcess, pi.dwProcessId) == -1) {
Fixed.

2017-02-08 20:13 UTC, bagajjal commented on contrib/win32/win32compat/misc.c
> +	CloseHandle(pi.hThread);
at line 365, pi is passed as an argument to the CreateProcessW() so the newly create process should close the handle?

2017-02-09 06:20 UTC, remittor commented on contrib/win32/win32compat/misc.c
> +	CloseHandle(pi.hThread);
**CreateProcessW** - particular function, which return two handles. Both handles must be closed.

2017-04-18 08:52 UTC, closed without merging