Reduce verbose
PowerShell/openssh-portable pull request #63
Opened 2017-01-24 01:31 UTC by bingbing8

1. remove more verbose output
2. add debug mode to collect trace

2017-01-26 20:24 UTC, bagajjal requested changes

2017-01-26 20:24 UTC, bagajjal commented on appveyor.yml
> +version: 0.0.8.0.{build}
I think we should read this from some file..
Ideally every time we release a new version we have to change the version number here so better to have the version number in a text file (which we change when ever we release a new version) and use that file content here so it eliminates the hardcoding of versioning here...

2017-01-26 20:24 UTC, bagajjal commented on appveyor.yml
> +  - ps: Write-Verbose "Restart computer completed!"
5 seconds is too less... what if it takes more than 5 seconds? we should first check whether the computer is rebooted or not before printing this log?

2017-01-26 20:24 UTC, bagajjal commented on contrib/win32/openssh/appveyor.psm1
> +      Set-BuildVariable TestPassed True
TestStatus might be more suitable.

2017-01-26 20:24 UTC, bagajjal commented on contrib/win32/openssh/appveyor.psm1
> +    <#if ( (-not (Test-Path "${env:ProgramFiles(x86)}\Windows Kits\8.1\Debuggers\" )) -and (-not (Test-Path "${env:ProgramFiles(x86)}\Windows Kits\10\Debuggers\" ))) {
if possible, remove the hard coding of paths like (Windows Kits\8.1, Windows Kits\10) because it yields to a maintenance headache..

2017-01-26 20:24 UTC, bagajjal commented on contrib/win32/openssh/appveyor.psm1
> +    $strToReplace = "Subsystem	sftp	C:/Program Files/OpenSSH/sftp-server.exe"
Don't hardcode the paths..

2017-01-26 20:24 UTC, bagajjal commented on contrib/win32/openssh/appveyor.psm1
> +Subsystem	sftp	$OpenSSHTestDir\sftp-server.exe
indentation

2017-01-27 00:19 UTC, bingbing8 commented on contrib/win32/openssh/appveyor.psm1
> +    $strToReplace = "Subsystem	sftp	C:/Program Files/OpenSSH/sftp-server.exe"
This is the string I need to search and replace

2017-01-27 00:59 UTC, bingbing8 commented on contrib/win32/openssh/appveyor.psm1
> +Subsystem	sftp	$OpenSSHTestDir\sftp-server.exe
The indentation at this section in the sshd_config file (both linux and windows) is tab. I followed the same.

2017-01-27 01:48 UTC, bingbing8 commented on contrib/win32/openssh/appveyor.psm1
> +    <#if ( (-not (Test-Path "${env:ProgramFiles(x86)}\Windows Kits\8.1\Debuggers\" )) -and (-not (Test-Path "${env:ProgramFiles(x86)}\Windows Kits\10\Debuggers\" ))) {
I will update when we need the debugger installed.

2017-01-27 06:43 UTC, bingbing8 commented
@bagajjal please see if you are okay with my response. Thanks for your comments

2017-01-27 17:49 UTC, bagajjal approved these changes

2017-01-27 18:47 UTC, merged