Fix CI Failures
PowerShell/openssh-portable pull request #636
Opened 2022-11-14 21:52 UTC by vthiebaut10

…able

# PR Summary

## PR Context

2022-11-15 22:19 UTC, PaulHigin requested changes

2022-11-15 22:19 UTC, PaulHigin commented on regress/pesterTests/SSH.Tests.ps1
>              # actual command line ssh target \"cmd\" /c \"echo hello\"
```suggestion
            # actual command line ssh target "cmd" /c "echo hello"
```

2022-11-15 22:19 UTC, PaulHigin commented on regress/pesterTests/SSH.Tests.ps1
>              # actual command line ssh target cd "$env:programfiles";pwd
```suggestion
            # actual command line ssh target cd "$env:programfiles\";pwd
```

2022-11-15 22:19 UTC, PaulHigin commented on regress/pesterTests/SSH.Tests.ps1
>              # actual command line ssh target dir "$env:programfiles";cd "$env:programfiles";pwd
```suggestion
            # actual command line ssh target dir "$env:programfiles\";cd "$env:programfiles\";pwd
```

2022-11-15 22:19 UTC, PaulHigin commented on regress/pesterTests/SSH.Tests.ps1
>              # actual command line ssh target echo "\"hello\""
```suggestion
            # actual command line ssh target echo "hello"
```

2022-11-15 22:19 UTC, PaulHigin commented on regress/pesterTests/SSH.Tests.ps1
>              # actual command line ssh target \"cmd\" /c \"echo \"hello\"\"
```suggestion
            # actual command line ssh target "cmd" /c "echo "hello""
```

2022-11-15 22:19 UTC, PaulHigin commented on regress/pesterTests/SSH.Tests.ps1
> +ssh
Is this a typo?

2022-11-16 15:21 UTC, vthiebaut10 commented on regress/pesterTests/SSH.Tests.ps1
> +ssh
Yes

2022-11-16 16:25 UTC, PaulHigin approved these changes
LGTM

2022-11-16 17:02 UTC, tgauth approved these changes

2022-11-16 17:26 UTC, merged