AF_UNIX IPC sockets client side support
PowerShell/openssh-portable pull request #84
Opened 2017-02-17 21:28 UTC by manojampalam

2017-02-17 23:25 UTC, bagajjal requested changes

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +fileio_connect(struct w32_io* pio, char* name) {
as per bsd coding guidelines the * should be associated with the variable name like struct w32_io *pio

2017-02-17 23:25 UTC, bagajjal commented on authfd.c
>  	if (fdp != NULL)
Please remove the one in agent.c
#define AGENT_PIPE_ID L"\\\\.\\pipe\\ssh-agent" (authfd.h)
#define SSH_AGENT_PIPE_NAME			L"\\\\.\\pipe\\ssh-agent" (agent.c)

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +		debug("fileio_connect called in unexpected state");
printing the pio->handle will help in debugging.

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/w32fd.c
> +		/* Ignore if handle is not valid yet */
please add some comments why will be come here if the handle is invalid..

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/wmain_sshd.c
> +	if (getenv("SSH_AUTH_SOCK") == NULL)
do we need this because wmain_common.c should be able to cover all the modules?

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +	if (WINHANDLE(pio) == 0 || WINHANDLE(pio) == INVALID_HANDLE_VALUE) {
when will be have the invalid handle? can you add some comments in which scenario this may happen...

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/inc/sys/un.h
> +#pragma once
we should decide on either using #include guard idiom in header files or #pragma once in all the files consistently..

2017-02-17 23:25 UTC, bagajjal commented on contrib/win32/win32compat/fileio.c
> +	SetHandleInformation(h, HANDLE_FLAG_INHERIT, pio->fd_flags & FD_CLOEXEC? 0 : HANDLE_FLAG_INHERIT);
need to check the return value here..

2017-02-18 04:46 UTC, manojampalam commented on contrib/win32/win32compat/wmain_sshd.c
> +	if (getenv("SSH_AUTH_SOCK") == NULL)
wmain_common is not part of sshd.

2017-02-18 04:46 UTC, manojampalam commented on contrib/win32/win32compat/inc/sys/un.h
> +#pragma once
Agree. I'll file a bug

2017-02-18 05:02 UTC, merged