Enable mprintf and fmprint in scp and sftp (https://github.com/PowerShell/Win32-OpenSSH/issues/534)
PowerShell/openssh-portable pull request #85
Opened 2017-02-18 07:52 UTC by bingbing8

printf still does not work well so still keep the overriding until find the cause.

2017-03-08 22:08 UTC, bagajjal requested changes

2017-03-08 22:08 UTC, bagajjal commented on utf8.c
> +#ifdef WINDOWS
Please move this functionality to posix layer and reduce the use of #ifdef windows..

2017-03-08 22:08 UTC, bagajjal commented on openbsd-compat/openssl-compat.c
> +	if (0x20 <= wc && wc <= 0x7e)
can you please add some comments, what this method is doing and how to interpret the hex codes (may be a URL that has these values will help us)..

2017-03-08 22:49 UTC, bingbing8 commented on openbsd-compat/openssl-compat.c
> +	if (0x20 <= wc && wc <= 0x7e)
for each range, I have comments near it. like /* Hiragana */. Is it okay?

2017-03-25 07:09 UTC, manojampalam commented
There were new changes to utf8.c implementation in Windows that makes these set of changes obsolete.

2017-03-25 07:09 UTC, closed without merging