support windows paths C:/Programdata/...
PowerShell/openssh-portable pull request #86
Opened 2017-03-02 22:54 UTC by discodance1

Currently it supports only cygwinpath format starting with a '/' more details in this issue:
https://github.com/PowerShell/Win32-OpenSSH/issues/548#issuecomment-283470155

2017-03-08 22:55 UTC, bagajjal requested changes

2017-03-08 22:55 UTC, bagajjal commented on servconf.c
> +			if (cp[len] != '/' && strcasecmp(cp + len, "none") != 0 && !(isalpha(cp[len]) && cp[len + 1] == ':' && cp[len+2] == '\'))
cp[len+2] is not required..

2017-03-09 00:12 UTC, discodance1 commented
Made the required changes.

2017-05-12 18:19 UTC, msftclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2018-05-10 19:19 UTC, closed without merging