fgets and utf8 functions for Windows
PowerShell/openssh-portable pull request #87
Opened 2017-03-06 20:52 UTC by manojampalam

2017-03-06 21:09 UTC, bagajjal requested changes

2017-03-06 21:09 UTC, bagajjal commented on sftp.c
> -			} else if (fgets(cmd, sizeof(cmd), infile) == NULL)
Please check this.. last time it didn't work when I try to read using fgetws()
https://github.com/PowerShell/Win32-OpenSSH/issues/529

2017-03-06 21:09 UTC, bagajjal commented on contrib/win32/win32compat/win32-utf8.c
> +	return 0;
return the return value of vfmprintf.. it is useful when we want to check the number of characters written...

2017-03-06 21:09 UTC, bagajjal commented on contrib/win32/win32compat/win32-utf8.c
> +	return 0;
return the return value of vfmprintf.. it is useful when we want to check the number of characters written...

2017-03-07 00:18 UTC, manojampalam commented on sftp.c
> -			} else if (fgets(cmd, sizeof(cmd), infile) == NULL)
If you look into implementation of w32_fgets, it only calls fgetws for console io, file io is still on fgets()

2017-03-07 00:18 UTC, merged