Vt100impact char
PowerShell/openssh-portable pull request #94
Opened 2017-03-20 17:42 UTC by bingbing8

To prevent screwing up terminal settings on windows when printing to the terminal, turn off the virtual terminal before printing to console. The files call these functions are from scp.c, sftp.c and sshconnect(calls smprintf only). The virtual termial are not enabled in scp and sftp on windows. Turning off it in vfmprintf is enough for the printing in sshconnect.c.

2017-03-21 23:29 UTC, bagajjal requested changes

2017-03-21 23:29 UTC, bagajjal commented on contrib/win32/win32compat/win32-utf8.c
> +HANDLE
Move this to posix_compat layer so that it can be reused.

2017-03-29 01:31 UTC, bingbing8 commented on contrib/win32/win32compat/win32-utf8.c
> +HANDLE
fixed.

2017-03-29 18:50 UTC, bagajjal approved these changes

2017-03-29 19:52 UTC, merged

2017-03-30 23:07 UTC, bingbing8 commented
https://github.com/PowerShell/openssh-portable/pull/94